import 'package:freezed_annotation/freezed_annotation.dart';
// This file is "main.dart"

// required: associates our `main.dart` with the code generated by Freezed
part 'environment.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'environment.g.dart';
@freezed
class Environment with _$Environment {
  factory Environment({
    required String baseUrl,
    required String appId,
    required String publicRSALogin,
    required String publicRSA,
  }) = _Environment;

  factory Environment.fromJson(Map<String, Object?> json)
  => _$EnvironmentFromJson(json);
}